### ISSUE TITLE
Правки

### ISSUE THREAD

**Issue by vsezbs** [moseffect21/okolo_kalyana#18]
- [ ] Не получается загрузить .svg изображения в админке (https://staging.okolokalyana.ru/admin/taplinks)
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/03a1b989-40ba-42e6-bf50-6c319a6d141a">

- [x] В админке на страницах:
- https://staging.okolokalyana.ru/admin/taplinks/create 
- https://staging.okolokalyana.ru/admin/taplinks/1/edit

Сделать селекторы у параметров: Category Id и Type

- [x] Добавить редактирование параметра little_role на страницы:
https://staging.okolokalyana.ru/admin/teams/8/edit
https://staging.okolokalyana.ru/admin/teams/create

**Comment by moseffect21** [comment]
`Не получается загрузить .svg изображения в админке` - не актуально. Обговорили, пришли к выводу, что не надо этого делать
