### ISSUE TITLE
Доработка бэка

### ISSUE THREAD

**Issue by moseffect21** [moseffect21/okolo_kalyana#4]
## В этой задаче ##
Дорабатываем бэк

- [x] - добавить в базу таблицу team, с полями :
**id** - int increment
 **name** - string
 **short_desc** - string
 **description** - long_text
 **photo** - string
 **tg_url** - string
 **vk_url** - string
 **inst_url** - string
 **youtube_url** - string
 
- [x] - добавить метод получения списка команды GET /api/v1/team

- [x] - добавить в таблицу articles поле **show_main** - boolean или int (нужно чтоб показывать статьи на главной странице)

- [x] - добавить таблицу partners с полями:
 **id** - int
  **name** - string
  **photo** - string
  **short_desc** - string
  **description** - long_text
  **show_main** - int
  
 - [x] - добавить таблицу product_categories с полями:
 **id** - int
 **name** - string
 **photo** - string
 **slug** - string
 **parent** - int
 
 - [x] - добавить таблицу products с полями:
 **id** - int
 **name** - string
 **description** - long_text
 **slug** - string
 **price** - string
 **attributes** - **ТУТ, ВНИМАНИЕ** нужно попробовать в эту переменную запихнуть !!!массив!!! объектов 
 (пример: 
[
  { name:"Производитель", value:"Россия" },
  { name:"Вес", value:"300 гр" }
] 

- [x] - добавить метод получения списка партнеров GET /api/v1/partners
- [x] - добавить метод получения списка категорий продуктов GET /api/v1/shop/categories
- [x] - добавить метод получения конкретной категории (в ответе, помимо данных о категории, должен быть привязан объект products - в котором лежит список продуктов данной категории) GET /api/v1/shop/categories/{id}
- [x] - добавить метод получения продукта(должен быть вложен объект с комментариями продукта **comments**) - /api/v1/shop/product/{id}
- [x] - добавить метод комментирования продукта - /api/v1/shop/product/{id}/comment

- [x] - **ТУТ ВНИМАНИЕ** нужно добавить метод /api/v1/main - который будет в ответе присылать объект вида:
{
 articles:{ объект статей с типом article },
 videos: { объект статей с типом video },
 product_categories: { объект категорий продуктов },
 partners: { объект со списком всех партнеров },
 team: { объект со списком команды }
}
**Примечание к методу выше** - в случае с объектами articles, videos, product_categories - в ответе должны быть объекты, у которых значение **show_main === 1**

- [ ] - Ну и последняя задача - **РАЗОБРАТЬСЯ С АДМИНКОЙ**  это прям супер-пупер важно

## Дополнение от 31.05.2021 ##
- [x] - добавить метод поиска статей/видео и прочего. /api/v1/search

## Дополнение от 12.06.2021 ##
- [x] - добавить к ответу на запрос /api/v1/article/{id} "подборки". Название поля выбери сам. Что это значит: В этом поле должен приходить массив с другими статьями, выбранными рандомно, в количестве до 5 штук. Нужно чтоб реализовать функционал "Смотрите так же".
- [x] - добавить таблицу likes с полями:
**id** - int
**user_id** - int
**article_id** - int
- [x] - добавить поле кол-ва лайков в таблице articles
- [x] - добавить метод "лайка" /api/v1/article/{id}/like - лайк могут поставить только авторизованные пользователи. Если лайк уже стоит, в этом же запросе надо его "снять", при снятии лайка - удаляешь запись. При лайке, создаешь в таблице likes запись, в которую заносишь id пользователи и id статьи. В таблице articles либо увеличиваешь кол-во лайков, либо уменьшаешь, в зависимости от того, поставил пользователь лайк или нет.
- [x] - добавить в таблицу acticles поле partner_id типа int,  и поле authors_id - тут нужно будет указать id авторов (их может быть несколько). Авторами являются зарегистрированные пользователи. Тобишь если мы хотим указать автора, мы просто вписываем в это поле id пользователя(напомню, их может быть несколько, так что, как вариант, можно указывать их через запятую)
- [x] - в ответе метода /api/v1/partners/{id} добавить поле articles и videos, в которых будут содержаться статьи и видео, у которых partner_id === id (Заготовку под это уже сделал)
![image](https://user-images.githubusercontent.com/52028340/121777530-50267880-cb9b-11eb-84e7-ea047903c407.png)
- [ ] - в ответе метода /api/v1/articles/{id} - в массиве комментариев так же должны приходить пользователи (если user_id существует)
- [x] - так же в массиве метода /api/v1/articles/{id} должны приходить авторы статьи/видео
`
authors:[
  {
    данные пользователя
  },
]
`
- [x] - добавить метод GET получения данных об авторе и его статей /api/v1/user/{id}. В ответе присылаем данные самого пользователя, внутри объект **articles** - в котором лежит массив статей которые он публиковал

**Comment by Deniskos3** [comment]
Нихуева так правок ты написал, минус пол дня на это -_-
